name: pytorch
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2025.11.4
  - expat=2.7.3
  - ld_impl_linux-64=2.44
  - libffi=3.4.4
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgomp=15.2.0
  - libnsl=2.0.0
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libuuid=1.41.5
  - libxcb=1.17.0
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.0.18
  - pip=25.2
  - pthread-stubs=0.3
  - python=3.10.19
  - readline=8.3
  - setuptools=80.9.0
  - sqlite=3.51.0
  - tk=8.6.15
  - wheel=0.45.1
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zlib=1.3.1
  - pip:
      - absl-py==2.3.1
      - albucore==0.0.24
      - albumentations==2.0.8
      - annotated-types==0.7.0
      - anyio==4.11.0
      - attrs==25.4.0
      - beautifulsoup4==4.14.2
      - bleach==6.3.0
      - certifi==2025.11.12
      - click==8.3.1
      - contourpy==1.3.2
      - cycler==0.12.1
      - defusedxml==0.7.1
      - et-xmlfile==2.0.0
      - fastjsonschema==2.21.2
      - filelock==3.20.0
      - fonttools==4.60.1
      - fsspec==2025.9.0
      - grpcio==1.76.0
      - h11==0.16.0
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==1.1.4
      - idna==3.11
      - ipywidgets==8.1.8
      - jinja2==3.1.6
      - joblib==1.5.2
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - jupyterlab-pygments==0.3.0
      - jupyterlab-widgets==3.0.16
      - kiwisolver==1.4.9
      - lightning-utilities==0.15.2
      - markdown==3.10
      - markupsafe==3.0.2
      - matplotlib==3.10.7
      - mistune==3.1.4
      - mpmath==1.3.0
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - networkx==3.4.2
      - numpy==2.1.2
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-nccl-cu12==2.27.5
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvshmem-cu12==3.4.5
      - nvidia-nvtx-cu12==12.8.90
      - opencv-python==4.12.0.88
      - opencv-python-headless==4.12.0.88
      - openpyxl==3.1.5
      - packaging==25.0
      - pandas==2.3.3
      - pandocfilters==1.5.1
      - pillow==12.0.0
      - protobuf==6.33.1
      - pydantic==2.12.4
      - pydantic-core==2.41.5
      - pyparsing==3.2.5
      - python-dateutil==2.9.0.post0
      - pytorch-triton==3.5.1+gitbfeb0668
      - pytz==2025.2
      - pyyaml==6.0.3
      - referencing==0.37.0
      - rpds-py==0.29.0
      - safetensors==0.6.2
      - scikit-learn==1.7.2
      - scipy==1.15.3
      - shellingham==1.5.4
      - simsimd==6.5.3
      - six==1.17.0
      - sniffio==1.3.1
      - soupsieve==2.8
      - stringzilla==4.2.3
      - sympy==1.14.0
      - tdqm==0.0.1
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - thop==0.1.1-2209072238
      - threadpoolctl==3.6.0
      - timm==1.0.22
      - tinycss2==1.4.0
      - torch==2.10.0.dev20251113+cu128
      - torchaudio==2.10.0.dev20251113+cu128
      - torchmetrics==1.8.2
      - torchvision==0.25.0.dev20251113+cu128
      - tqdm==4.67.1
      - typer-slim==0.20.0
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - tzdata==2025.2
      - webencodings==0.5.1
      - werkzeug==3.1.3
      - widgetsnbextension==4.0.15
      - xlsxwriter==3.2.9
prefix: /home/calculon/miniconda3/envs/pytorch
